# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            ForgottenGlory's Modlists 
tagline:          
description:      
url:              https://github.com/karloespiritu/blackdoc
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           ForgottenGlory
  url:            

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
 
# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/karloespiritu/blackdoc
